
-- Food item table
CREATE FOOD(
    FOOD_ITEM_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FOOD_ITEM_NAME VARCHAR UNIQUE NOT NULL,
    LINK VARCHAR UNIQUE NOT NULL
);

CREATE INDEX item ON FOOD(FOOD_ITEM_NAME);
CREATE INDEX link ON FOOD(LINK);

-- Ingredient table
CREATE INGREDIENTS(
    INGREDIENT_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FOOD_ITEM_ID BIGINT NOT NULL,
    INGREDIENT VARCHAR NOT NULL,
    MEASUREMENT VARCHAR NOT NULL,
    FOREIGN KEY (FOOD_ITEM_ID) REFERENCES INGREDIENTS(FOOD_ITEM_ID)
);
